package
{
	public final class TestData
	{
		public static const FLOORS:XML = 
			<floors>
				<floor>
					<id>1</id>
					<label>一楼</label>
					<coordinate>m|0-0,l|1000-0,l|1000-1000,l|0-1000,l|0-0</coordinate>
					<color>0xCCCCCC</color>
					<order>1</order>
				</floor>
				<floor>
					<id>2</id>
					<label>二楼</label>
					<coordinate>m|0-0,l|1000-0,l|1000-1000,l|0-1000,l|0-0</coordinate>
					<color>0xCCCCCC</color>
					<order>2</order>
				</floor>
			</floors>;
		
		public static const POSITIONS:XML = 
			<positions>
				<position>
					<id>1</id>
					<color>0xFF0000</color>
					<coordinate>m|100-100,l|200-100,l|200-300,l|100-300,l|100-100</coordinate>
					<icon></icon>
					<iconOffsetX></iconOffsetX>
					<iconOffsetY></iconOffsetY>
					<iconRotation></iconRotation>
					<iconScale></iconScale>
					<iconSuspend></iconSuspend>
					<iconVisible>true</iconVisible>
					<label>位置1</label>
					<labelColor>0xFFFFFF</labelColor>
					<labelOffsetX>0</labelOffsetX>
					<labelOffsetY>50</labelOffsetY>
					<labelRotation>0</labelRotation>
					<labelScale>1.5</labelScale>
					<labelVisible>true</labelVisible>
					<serial>192168001016-20150802142503-4A3C0DRW</serial>
					<thick>50</thick>
					<floor_id>1</floor_id>
					<position_type_id>1</position_type_id>
				</position>
				<position>
					<id>2</id>
					<color>0x0000FF</color>
					<coordinate>m|300-100,l|500-100,l|500-300,l|300-300,l|300-100,m|350-150,l|450-150,l|450-250,l|350-250,l|350-150</coordinate>
					<icon></icon>
					<iconOffsetX></iconOffsetX>
					<iconOffsetY></iconOffsetY>
					<iconRotation></iconRotation>
					<iconScale></iconScale>
					<iconSuspend></iconSuspend>
					<iconVisible></iconVisible>
					<label>位置2</label>
					<labelColor>0xFFFFFF</labelColor>
					<labelOffsetX></labelOffsetX>
					<labelOffsetY>80</labelOffsetY>
					<labelRotation></labelRotation>
					<labelScale>1.5</labelScale>
					<labelVisible>true</labelVisible>
					<serial>192168001016-20150802142503-BS84JT6Q</serial>
					<thick>50</thick>
					<floor_id>1</floor_id>
					<position_type_id>1</position_type_id>
				</position>
				<position>
					<id>3</id>
					<color>0xFF0000</color>
					<coordinate>m|600-100,l|700-100,l|700-200,l|600-200,l|600-100</coordinate>
					<icon></icon>
					<iconOffsetX></iconOffsetX>
					<iconOffsetY></iconOffsetY>
					<iconRotation></iconRotation>
					<iconScale></iconScale>
					<iconSuspend></iconSuspend>
					<iconVisible></iconVisible>
					<label>位置3</label>
					<labelColor>0xFFFFFF</labelColor>
					<labelOffsetX></labelOffsetX>
					<labelOffsetY></labelOffsetY>
					<labelRotation></labelRotation>
					<labelScale>1.5</labelScale>
					<labelVisible>true</labelVisible>
					<serial>192168001016-20150802142503-S843J4HS</serial>
					<thick>50</thick>
					<floor_id>1</floor_id>
					<position_type_id>1</position_type_id>
				</position>
				<position>
					<id>4</id>
					<color>0xFF00FF</color>
					<coordinate>m|100-600,c|300-600$200-500,l|300-700,l|100-700,l|100-600</coordinate>
					<icon></icon>
					<iconOffsetX></iconOffsetX>
					<iconOffsetY></iconOffsetY>
					<iconRotation></iconRotation>
					<iconScale></iconScale>
					<iconSuspend></iconSuspend>
					<iconVisible></iconVisible>
					<label>位置4</label>
					<labelColor>0xFFFFFF</labelColor>
					<labelOffsetX></labelOffsetX>
					<labelOffsetY></labelOffsetY>
					<labelRotation></labelRotation>
					<labelScale>1.5</labelScale>
					<labelVisible>true</labelVisible>
					<serial>192168001016-20150802142503-AD3R5T7Y</serial>
					<thick>50</thick>
					<floor_id>2</floor_id>
					<position_type_id>2</position_type_id>
				</position>
			</positions>;
		
		public static const POSITION_TYPES:XML = 
			<positionTypes>
				<positionType>
					<id>1</id>
					<name>店铺</name>
					<code>entity</code>
				</positionType>
				<positionType>
					<id>2</id>
					<name>天井</name>
					<code>hollow</code>
				</positionType>
				<positionType>
					<id>3</id>
					<name>洗手间</name>
					<code>unseen</code>
				</positionType>
				<positionType>
					<id>4</id>
					<name>入口</name>
					<code>terrain</code>
				</positionType>
			</positionTypes>;
	}
}